export const REDUCER_NAME = {
    SET_INITIAL_PRODUCTS_LIST: "SET_INITIAL_PRODUCTS_LIST",
    SET_ERROR_MESSAGE_PRODUCTS_LIST: "SET_ERROR_MESSAGE_PRODUCTS_LIST",
    SET_ERROR_MESSAGE_SHOPING_LIST: "SET_ERROR_MESSAGE_SHOPING_LIST",
    SET_SHOPING_LIST: "SET_SHOPING_LIST",
    SET_LOADING_SHOPING_LIST: "SET_LOADING_SHOPING_LIST",
    SET_FILTERED_PRODUCT_LIST: "SET_FILTERED_PRODUCT_LIST",
    SET_INITIAL_FILTERED_PRODUCT_LIST: "SET_INITIAL_FILTERED_PRODUCT_LIST",

}